// src/domain/error-map.ts
export const ERROR_STATUS_MAP: Record<string, number> = {
  VALIDATION_ERROR: 400,
  AUTH_INVALID_CREDENTIALS: 401,
  EMAIL_ALREADY_USED: 409,
  TOKEN_INVALID: 401,
  TOKEN_EXPIRED: 401,
  USER_NOT_FOUND: 404,
  GROUP_NOT_FOUND: 404,
  EXPENSE_NOT_FOUND: 404,
  SETTLEMENT_NOT_READY: 400,
  PERMISSION_DENIED: 403,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
};
